### ISSUE TITLE
Consider adding more agents or other solution to speed up JS tests

### ISSUE THREAD

**Issue by yurtsevich-sbb** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.diff-tool#232]
### Description

JS tests using Playwright (3 runs per a test - for 3 browsers) takes pretty much time:

```
[INFO] Running 132 tests using 1 worker
[INFO] ...
[INFO]   132 passed (8.1m)
```

### Motivation

JS tests using Playwright (3 runs per a test - for 3 browsers) takes pretty much time

**Comment by ariwk** [comment]
# Configuring Playwright Workers in GitHub Actions

When running Playwright tests, the default behavior is to use multiple workers locally based on your CPU cores, but GitHub Actions might be limiting it to a single worker.

## Solution

You can explicitly configure the number of workers in your Playwright configuration or via command line arguments when running in GitHub Actions:

### Option 1: Update your playwright.config.ts/js file

```typescript
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  // Other config options...
  workers: process.env.CI ? 2 : undefined, // Use 2 workers in CI, or auto-detect locally
});
```

### Option 2: Specify workers in your GitHub Actions workflow

```yaml
- name: Run Playwright tests
  run: npx playwright test --workers=2
```

### Option 3: Set environment variable in GitHub Actions

```yaml
- name: Run Playwright tests
  env:
    PLAYWRIGHT_WORKERS: 2
  run: npx playwright test
```

## Important Considerations

1. GitHub-hosted runners have different CPU configurations:
   - Ubuntu runners: 2 cores
   - Windows runners: 2 cores
   - macOS runners: 3 cores (4 cores for macOS-latest)

2. Be mindful of memory constraints when increasing workers in CI environments.

3. For larger test suites, consider using sharding instead of just increasing workers:
   ```yaml
   - name: Run Playwright tests (shard 1/2)
     run: npx playwright test --shard=1/2
   
   - name: Run Playwright tests (shard 2/2)
     run: npx playwright test --shard=2/2
   ```

Choose the option that best fits your workflow and test suite requirements.
